language: objective-c
osx_image: xcode8.2
env:
  global:
    - ORGANIZATION=rentpath
    - REPOSITORY=Atlas
    - FRAMEWORK_NAME=$REPOSITORY
    # GITHUB_ACCESS_TOKEN
    - secure: "HhtG+kd6vXj4vsVI1gYrnIkdFO179he6RzH5UvaBEMJl1F4jAtoSXFLKHu3H+23HcB6GYaBilGLopzhaUXRCSV6It5Fm4no56tCwOsHBTJsZeb4NBlmMuhksMaQwGttZieLVfxt/SE+C47TihT73mqGvjwVtrXGrj54LKHQnnMQIMS5b4ef30VUMJ2VM66EVzrut1DVrN1yirQWPKjMd934hvOWmVDFij1GZX/J1UMQbtJv91uPxhl1mN7HiorNQ0TgdcHgBKXWRj0ZTSFr9KWFdArQFcFYTRN+7xTXue8vT7LbcDwdHtfGefENW6Y1QaoK8Sb8ATJ+/Y2R/Ez93lVNgm8RADRekwkSHH/e/FGyiOu2HmpOkR2mk+ZNm1yY3HbRT64nwUHx12hURjdDnKv4W2qENb/XWFszt1Z3rRhcK7PuBVsDlfXQMD2HRBPzXL+BB4VTJbOocGf8WRg3aUF9fOKxPTi6FJ/c7OnRsPwGS/EZFuugzely7XwCLZR/v8djfffKPwo92kaMtxgKFyWQ/SPSU57gvv8R8+lOPyahE5EjmHmsOimgvcYse3J5n5wF/1gn3uE/aU+J9uyOFOOISRGENQAKWNu6Y2AL5nE/bvlS1WNXW82UTkKN/HhmEBpt5N+z4gqSdvkwwPhJotGRaRrHnmr8WNpwlsIbfWO0="
    # PIVOTAL_TOKEN
    - secure: "K7Si7+ZfC64TmDg8iyGtfSj1zBMMfutVUJE35J1wlKJOJ9VZobzurYG9VpTliNKtD7JXCA3AI7cSFMw0wLorwqIBBB4J/0vcnpLGs1aWC6Fv3SvvH6y58jyJzILY9GEkY9eRH1VXify0qVn8CoI2ZC3qIpZr5WyGQj/XaoZurXKU6RudeH+9fAIXCL/DvWgKj+o5Fus+/gD9lFBC+wGLq8hKOpn79SU28UQpejH9ToUWOt6huVo3BffgXMHjU+v4qAs5TmasLuosy3Gz9Fdxf/WoKNX3WoKgcTJoV4pQ7FeT9CMNO2QRIyu0T5cig4WwjVvCwlbtO6q6jkgBjCnltvE2YFXn4LDSXMtlB+C1Y2H5JnwDoSuWUt5cqypASGaJBL/oz24BW3WO+mO0x5IEbymZIyDO+A8nuSMZgebbW+RBXHi6eY/W9cinesLn5rX+/mkL3aV73CbSZb0D/zCjQ5hfhQP+79QTo3E/GXqmgQJO+nNi1Iq2RLK2zMt5W0G0s8DL/YARrd+vPT8VuZNLWb0Vy60sawxQhs4zX8YcJ80w0bL1Al6yGcaprSKW3OPwHxDqq4Day4EIEeeEtL8mHmXyh2NtmcGv/u0jhfxG2Fp64SjMldOgZ4wJwJ9a9MPK6AKfHj5DrE4iH1Ton9ty7LjEs3Q6BQ1yIRe6sJiO9a0="
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew outdated swiftlint || brew upgrade swiftlint
before_script:
  - carthage bootstrap --use-ssh --platform iOS
script: 
  - xcodebuild -project Atlas.xcodeproj -scheme Atlas -destination "name=iPhone 7" build test | xcpretty -c; test ${PIPESTATUS[0]} -eq 0
before_deploy:
  - carthage build --no-skip-current --platform iOS
  - carthage archive $FRAMEWORK_NAME
after_success:
  - sleep 5
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export OLD_GIT_TAG=$(git tag --sort version:refname | tail -n1)
  - export NEW_GIT_TAG=$(echo $OLD_GIT_TAG | (IFS=".$IFS" ; read a b c && echo $a.$b.$((c + 1))))
  - git tag $NEW_GIT_TAG -a -m "Generated tag $NEW_GIT_TAG"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then git push --quiet https://$GITHUB_ACCESS_TOKEN@github.com/$ORGANIZATION/$REPOSITORY $NEW_GIT_TAG > /dev/null 2>&1; fi
deploy:
  provider: releases
  api_key:
    secure: PVzUBB4ZG++3vCAgrhx7CUY/jyzKCUx90y5B2ifr7yDiZhp5ft/JB4Q+qREPBojeHygSIOClfdqn5w1ZBHNRA+aCYy9yrVVzDnr3qhZK77OhArJPNz0cA9X/vIom5ruLucbo5HG1DiVFCueIpIqozr1Xln/gV5tw6ra/7mvWaPsi5vh9TntIJDLKfBpA5IxG4GT1uo4FzAklWvQ6LrjutHllmD7W1rxJ0UreZpluUHjFAzbV5NOZxIjpg3iR8s10OTWEEYBAIurMW30DMfr38BznGHsgbgclo3J87ip9SF/DXjeZCfzzOuoU/FshDKVSPa2FEi3OniqFSCrlNtPRJspqUmVnJD+o8IZ05U39nl1A0PY2wAGTJ3tlKsXNGAa+mCKUDLzuzntUuEsLxSWL7Zwk4sRh5GLmWXfPGMtAp7gA9gTEhAJr930J0vuAH96Q2fVeW4YTYcc1SUx6NxCxYqDnXeYulHx4RXFcTxWHCwGOzWTvpE8QvwUlwAYBPSu4hwIygu7gOQBVSYMd4oKZefVG0KheyylO5CPi/3kK3eZhDEGSp4lxuM5hdckXWF+K3c7pqTL22deZZknxjWGhyJ+/FkSt7j6frUfAyQoWpL9lkBneOuqQCPlFLMMhisC4aQJZXR17gTIocGNSv7RY5PuEd3tn7eU10GR/KUylxK0=
  file: $REPOSITORY.framework.zip
  skip_cleanup: true
  on:
    repo: $ORGANIZATION/$REPOSITORY
    tags: true
